---
- name: "Bulding Docker Image"
  become: true
  hosts: build
  vars_files:
    - docker.vars
  vars:
    packages:
      - docker
      - git
      - python3
      - python3-pip
    app_dir: "./flask-app/"
    copy_dir: "/var/flaskapp"
    image_name: "akshaygkrishnan/githubaction-ansible-app"
  tasks:
    
    - name: "Build - Package Installation"
      yum:
        name: "{{packages}}"
        state: present
            
            
    - name: "Build - Adding Ec2-user to Docker Group"
      user:
        name: "ec2-user"
        groups: 
          - "docker"
        append: yes
            
            
    - name: "Build - Starting/Enabling Docker Service"
      service:
        name: docker
        state: started
        enabled: true    
    
    - name: "Build - Installing Python Docker Module"
      become: false
      pip:
        name: docker
        state: present

    - name: "Build - Creating Copy Directory {{ copy_dir }}"
      file:
        path: "{{ copy_dir }}"
        state: directory
         
    - name: "Build - Copying File to Build Server"
      copy:
        src: "{{ app_dir }}"
        dest: "{{ copy_dir }}"
      register: copy_status  
    
    - name: "Build - Loging to Docker-hub Account"
      when: copy_status.changed == true
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        state: present
    
    - name: "Build - Creating Docker Image And Push To Docker-hub"
      when: copy_status.changed == true
      community.docker.docker_image:
        source: build
        build:
          path: "{{ copy_dir }}"
          pull: yes
        name: "{{ image_name }}"
        tag: "{{ item }}"
        push: true
        force_tag: yes
        force_source: yes
      with_items:
        - latest 
        
    - name: "Build - Removing Docker Image"
      when: copy_status.changed == true
      community.docker.docker_image:
        state: absent
        name: "{{ image_name }}"
        tag: "{{ item }}"
      with_items:
        - latest 
        
        
    - name: "Build - Logout to Docker-hub Account"
      when: copy_status.changed == true
      community.docker.docker_login:
        username: "{{ docker_user }}"
        password: "{{ docker_password }}"
        state: absent  
            
            
- name: "Running Image On The Test Server"
  hosts: test
  become: true
  vars:
    image_name: "akshaygkrishnan/githubaction-ansible-app"
    packages:
      - docker
      - python3-pip
  tasks:
    

    - name: "Test - Installing Packages"
      yum:
        name: "{{ packages }}"
        state: present
    
    - name: "Test - Adding Ec2-user to docker group"
      user:
        name: "ec2-user"
        groups:
          - docker
        append: true       
            
    - name: "Test - Installing Python Extension For Docker"
      become: false
      pip:
        name: docker
                   
    - name: "Test - Docker service restart/enable"
      service:
        name: docker
        state: started
        enabled: true

    - name: "Test - Pulling Docker Image"
      community.docker.docker_image:
        name: "{{ image_name }}:latest"
        source: pull
        force_source: true
      register: image_status      
    
    - name: "Test- Run Container"
      when: image_status.changed == true     
      community.docker.docker_container:
        name: flaskapp
        image: "{{ image_name }}:latest"
        recreate: yes
        published_ports:
          - "80:5000"


